apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang-api
  template:
    metadata:
      labels:
        app: golang-api
    spec:
      containers:
        - name: golang-api
          image: golang-api:latest
          ports:
            - containerPort: 7000
          env:
            - name: DB_USER
              value: "user"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_HOST
              value: "db"
            - name: DB_NAME
              value: "golang_api"
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: golang-api
spec:
  selector:
    app: golang-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
  type: ClusterIP
