---
apiVersion: v1
kind: Namespace
metadata:
  name: magic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: magic
  name: magic-calculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: magic-calculator
      tier: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: magic-calculator
        tier: frontend
    spec:
      containers:
      - env:
        - name: API_URL
          value: http://calculadora-api.calculator.svc.cluster.local/backend
        image: __IMAGEM__
        imagePullPolicy: IfNotPresent
        name: magic-calculator
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /frontend
            port: http
          initialDelaySeconds: 30
          failureThreshold: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /frontend
            port: http
          initialDelaySeconds: 30
          failureThreshold: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  namespace: magic
  name: magic-calculator
  labels:
    app.type.monitor: jvm-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: magic-calculator
    tier: frontend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: magic-calculator
  name: magic-calculator-nlb
  namespace: magic
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: magic-calculator
    tier: frontend
  type: LoadBalancer
