---
apiVersion: v1
kind: Namespace
metadata:
  name: magic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: magic
  name: magic-calculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: magic-calculator
      tier: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: magic-calculator
        tier: frontend
    spec:
      containers:
      - env:
        - name: API_URL
          value: http://calculadora-api.calculator.svc.cluster.local/backend
        image: __IMAGEM__
        imagePullPolicy: IfNotPresent
        name: magic-calculator
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /frontend
            port: http
          initialDelaySeconds: 30
          failureThreshold: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /frontend
            port: http
          initialDelaySeconds: 30
          failureThreshold: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  namespace: magic
  name: magic-calculator
  labels:
    app.type.monitor: jvm-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: magic-calculator
    tier: frontend
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: magic
  name: ingress-alb-magic-calculator
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          frontend:
            service:
              name: magic-calculator
              port:
                number: 80

