name: "APPS - CI/CD"

on:
  workflow_call:
    inputs:
      aws-region:
        type: string
        required: true
      eks-cluster-name:
        type: string
        required: true
      repository-name:
        type: string
        required: true
      app-path:
        type: string
        required: true
    secrets:
      dockerhub-username:
        required: true
      dockerhub-token:
        required: true
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      db-user:
        required: true
      db-password:
        required: true



jobs:
  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Autenticação no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}

      - name: Construção da imagem Docker
        uses: docker/build-push-action@v6
        with: 
          context: ./${{ inputs.app-path }}
          file: ./${{ inputs.app-path }}/Dockerfile
          push: true
          tags: |
            wandermaia/${{ inputs.repository-name }}:${{ github.run_number }}
            wandermaia/${{ inputs.repository-name }}:latest



  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      # Essa action troca os valores entre __ pelas variáveis informadas nos arquivos da pasta.
      # https://github.com/marketplace/actions/expand-tokens
      #
      - uses: sandersaares-actions/expand-tokens@master
        env:
          USUARIO_BANCO: ${{ secrets.db-user }}
          SENHA_BANCO: ${{ secrets.db-password }}
          IMAGEM: wandermaia/${{ inputs.repository-name }}:${{ github.run_number }} # imagem no formato wandermaia/calculadora-api:3
        with:
          path: ${{ inputs.app-path }}
          recursive: true


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}


      # Aplicando os manifestos no eks
      - name: Deploy to EKS
        working-directory: ./${{ inputs.app-path }}
        run: |
          aws eks update-kubeconfig --name ${{ inputs.eks-cluster-name }} --region ${{ inputs.aws-region }}

          echo -e "\nArquivo de maifesto:\n"
          cat ./k8s/manifesto.yaml
          
          kubectl apply -f ./k8s/manifesto.yaml

          echo -e "\nTestando AWS CLI:\n"
          aws s3 ls
          
